name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC 0:00执行
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync with upstream
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
